name: Run tests
on:
  push:
    branches:
      - "test_workflow*"
  pull_request:
    branches:
      - "master"

jobs:
  run_tests:
    name: Run tests on (ubuntu-latest, Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Run in all these versions of Python
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install QuakeMigrate
        run: |
          python -m pip install --upgrade pip
          pip install .
      
      - name: Install NonLinLoc
        run: |
          curl http://alomax.free.fr/nlloc/soft7.00/tar/NLL7.00_src.tgz -o NLL7.00_src.tgz
          tar -xzvf NLL7.00_src.tgz
          cd src
          mkdir bin
          make -R all
          mv Vel2Grid Grid2Time bin/.
          echo "$PWD/bin" >> $GITHUB_PATH

      - name: Run tests
        working-directory: ./tests
        run: |
          python test_import.py
          python run_test_examples.py
          python test_benchmarks.py
